### ISSUE TITLE
@media

### ISSUE THREAD

**Issue by JonDum** [dciccale/css2stylus.js#7] opened 2014-05-30 17:44 UTC
So @media tags aren't rendering so well right now.

input: 
```css
@media only screen and (max-width: 998px) {
  .page.grid {
    padding: 0% 4%;
  }
}
```

output:
```
@media
  only
    screen
      and
        (max-width
          &:
            998px)
              .page.grid {
    padding 0% 4%
```

It looks like the code is treating the spaces as additional selectors because it's getting through to line 109 `selectors = selector.split(/[\s]+/);`

Maybe we should add another check to the `if` statement on line 99 to see if the selector starts with `@media` then process the contents of that block recursively?

The way it is now doing that recursively would require a lot of rewriting. Maybe there's a better way. What are your thoughts?

**Comment by JaKXz** [comment] 2015-01-27 05:52
I'm seeing this issue as well.

**Comment by dciccale** [comment] 2015-01-29 10:50
Seems a pretty good fix to do by adding an additional check. Didn't have the time yet to implement it. I will try it whenever I have time for this, please feel free to contribute

**Comment by KyleKing** [comment] 2015-04-26 22:51
I'm still having this issue as well, given:
```css
@media(min-width:1200px) {
    .timeline>li {
        min-height: 170px;
    }
}
```

Css2stylus outputs:
```stylus
@media(min-width
  &:1200px)
    .timeline>li {
        min-height 170px
```

**Comment by DenisDubovitskiy** [comment] 2015-06-24 20:23
Still having this issue too
```stylus

@media
    (max-width
      &:
        767px)
          before {
        left 40px

ul
  &.timeline
    & > li
      margin-bottom 20px
      position relative
      width 100%
      float left
      clear left
```

**Comment by dciccale** [comment] 2015-07-30 12:49
this needs to be addressed in a special case. open to contributions :)

will try to fix it at some point

**Comment by JonDum** [comment] 2015-07-31 09:42
Honestly, it's not a feature, but a straight up bug. :|

**Comment by dciccale** [comment] 2015-07-31 10:38
well as I see it is a feature. because this version i never made any special implementation for handling media queries. so if support is something is needed to be implemented (not fixed) is a feature. not a bug

**Comment by dciccale** [comment] 2015-07-31 10:39
and what i meant above in my previous comment by "fix" was about fixing the github issue by implementing this feature.

thanks for the contribution

**Comment by NeXTs** [comment] 2015-08-12 15:29
+1
I also faced `@media` issue

**Comment by KeitIG** [comment] 2015-10-28 09:08
Hi, any news on this ?

**Comment by dciccale** [comment] 2015-10-28 09:10
i am pretty busy to handle this now, please feel free to contribute.

**Comment by KyleKing** [comment] 2015-12-12 23:41
I just submitted a pull request that should fix this issue

**Closed** 2015-12-13 15:05 UTC
Labels: feature
